on: [push,workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      - name: get pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.23.0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: pnpm
      - name: Upgrade JS dependencies
        # ADD YOUR CUSTOM DEPENDENCY UPGRADE COMMANDS BELOW
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: pnpm
      - name: Install JS dependencies and build
        # ADD YOUR CUSTOM DEPENDENCY UPGRADE COMMANDS BELOW
        run: |
          pnpm install && pnpm build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: read-bibleineverylanguage-org
          directory: dist # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
