on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set environment variable
        run: |
          if [ ${{ github.ref }} = 'refs/heads/read-prod' ]; then
            echo "PUBLIC_WACS_URL=https://content.bibletranslationtools.org" >> $GITHUB_ENV
          else
            echo "PUBLIC_WACS_URL=https://wacs-dev.bibletranslationtools.org" >> $GITHUB_ENV
          fi
      - name: get pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.13.2
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: pnpm
      - name: Install JS dependencies and build
        # ADD YOUR CUSTOM DEPENDENCY UPGRADE COMMANDS BELOW
        run: |
          pnpm install && pnpm build
        env:
          PUBLIC_WACS_URL: ${{ env.PUBLIC_WACS_URL }}
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=read-bibleineverylanguage-org --upload-source-maps=true